from typing import List

from oop_models._types import Evidence


class WorkingMemory():
    """
    Tracks dialog state, which is represented using six-tuple (q, e, o, u, f, h_q)

    - q is user query
    - e is evidence for q, consolidated from **Knowledge Consolidator (KC)**
    - o is a set of candidate responses for q
    - u is a score assessing the utility of each candidate response in o. **Generated by Utility (U)**
    - f is verbalized feedback to guide LLM to improve its utility (I am assuming f has the same size as o as well). **Generated by Utility (U)**
    - h_q is the dialog history before q
    """

    def __init__(self) -> None:
        self.q: str = ''
        self.e: List[Evidence] = []
        self.h_q: List[str] = []

        self.o: List[str] = []
        self.u: List[float] = [] # Same size as o
        self.f: List[str] = [] # Same size as o

